{
  "item.arcane.arcane_shard": "Осколок Аркана",
  "item.arcane.arcane_crystal": "Кристалл Аркана",
  "item.arcane.eiro_heart": "Сердце Эйро",
  "item.arcane.sair_katana": "Катана Саира",
  "key.arcane.transform": "Превращение",
  "key.categories.arcane": "Arcane",
  "message.arcane.unlocked_sair": "§5Сила Аркана приняла тебя. Нажми Alt, чтобы стать Саиром.",
  "message.arcane.unlocked_eiro": "§4Пламя Эйро проснулось в тебе. Нажми Alt, чтобы показать, кто ты.",
  "message.arcane.power_removed": "§7Сила покинула тебя.",
  "message.arcane.already_has": "Эта сила уже в тебе",
  "message.arcane.no_power": "У тебя нет силы для превращения",
  "message.arcane.cooldown": "Превращение перезаряжается: %s с",
  "message.arcane.on_sair": "§5Ты стал Саиром.",
  "message.arcane.on_eiro": "§4Ты стал Эйро.",
  "message.arcane.off": "§7Ты вернулся в обычную форму.",
  "message.arcane.not_sair": "Катана подчиняется только Саиру",
  "message.arcane.legend_fell": "§6Легенда пала! %s победил %s и забрал Кристалл Аркана!",
  "key.arcane.ability": "Способность (бросок блока)",
  "message.arcane.ability_eiro_only": "Способность доступна только в форме Эйро",
  "message.arcane.ability_cooldown": "Способность перезаряжается: %s с",
  "message.arcane.no_block": "Смотри на блок (не дальше 6 блоков)",
  "message.arcane.bad_block": "Этот блок нельзя поднять"
}